(SUP-2115) Add postgres bloat size and percents
puppetlabs/puppetlabs-puppet_metrics_collector pull request #175
Opened 2023-01-18 23:15 UTC by m0dular

2023-01-30 11:17 UTC, MartyEwings requested changes
iv looked and tested this one, it looks good? nothing appears broken, but i cant evaluate the numbers it produces? id be happy to merge if you are happy with the math, once you rebase over the last change

2023-02-01 16:56 UTC, MartyEwings submitted a review, later dismissed

2023-02-04 00:20 UTC, Sharpie submitted a review, later dismissed
Looks good 👍 

Ran the queries under `EXPLAIN (ANALYZE, BUFFERS)` and they do read 100+ MB of data from disk --- but most of the usage appears to come out of the `pg_class` and `pg_attribute` system tables, the contents of which don't change unless the database schema changes.

Which is a long-winded way of saying it does not look like the resource consumption of these queries will scale along with customer data sizes.

2023-02-04 14:03 UTC, MartyEwings commented
i resolved a conflict in metrics tidy, there was just conflicting whitespace around the top

2023-02-06 10:43 UTC, MartyEwings approved these changes

2023-02-06 10:43 UTC, merged